# Generated by Django 4.2 on 2023-05-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'log'), (1, 'info'), (2, 'warn'), (3, 'error')], default=0, verbose_name='type'),
        ),
    ]
