# Generated by Django 4.2 on 2023-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('desc', models.TextField(blank=True, verbose_name='desc')),
                ('material', models.CharField(max_length=64, verbose_name='material')),
                ('unit', models.CharField(max_length=64, verbose_name='unit')),
                ('info', models.JSONField(blank=True, default=dict, verbose_name='info')),
            ],
            options={
                'verbose_name': 'Material',
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='material_ma_name_57b495_idx'),
        ),
    ]
