# Generated by Django 4.2 on 2023-05-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=90, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=90, verbose_name='Value'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['key'], name='management__key_db1dc8_idx'),
        ),
    ]
