# Generated by Django 4.2 on 2023-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storen', models.PositiveSmallIntegerField(verbose_name='N')),
                ('storex', models.PositiveSmallIntegerField(verbose_name='X')),
                ('storey', models.PositiveSmallIntegerField(verbose_name='Y')),
                ('status', models.CharField(choices=[('EMTY', 'Empty/空'), ('RSVD', 'Reserved/已预订'), ('OCUP', 'Occupied/已占用'), ('LOCK', 'Locked/已锁定')], default='EMTY', max_length=4, verbose_name='Status')),
                ('goods', models.JSONField(verbose_name='GoodsData')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['storen', 'storey', 'storex'], name='store_store_storen_e48b71_idx'),
        ),
    ]
