# Generated by Django 4.2 on 2023-05-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='goods',
        ),
        migrations.AddField(
            model_name='store',
            name='details',
            field=models.JSONField(default='{}', verbose_name='GoodDetail'),
        ),
        migrations.AddField(
            model_name='store',
            name='good',
            field=models.CharField(default='bolt', max_length=90, verbose_name='GoodName'),
            preserve_default=False,
        ),
    ]
