# Generated by Django 4.2 on 2023-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_material'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='store_store_status_565347_idx'),
        ),
    ]
